# Seed list of 50 prominent known AI startups for entity resolution
SEED_STARTUPS = [
    "OpenAI",
    "Anthropic",
    "Cohere",
    "Perplexity",
    "Mistral AI",
    "Scale AI",
    "Hugging Face",
    "Midjourney",
    "Replicate",
    "Together AI",
    "ElevenLabs",
    "Runway",
    "Character.ai",
    "Adept",
    "Jasper",
    "Harvey",
    "Phind",
    "Cursor",
    "Codeium",
    "Tabnine",
    "Magic",
    "Inflection AI",
    "CoreWeave",
    "Shield AI",
    "Synthesia",
    "DeepL",
    "AI21 Labs",
    "Anyscale",
    "MosaicML",
    "Writer",
    "RunPod",
    "Glean",
    "Sana",
    "LangChain",
    "LlamaIndex",
    "Pinecone",
    "Weaviate",
    "Qdrant",
    "Chroma",
    "Milvus",
    "H2O.ai",
    "Snorkel AI",
    "Dataiku",
    "Weights & Biases",
    "Comet ML",
    "Arthur AI",
    "Arize AI",
    "Fiddler AI",
    "Banzai Cloud",
    "Predibase"
]
